In [1]:
print("Hello Python")

Hello Python


In [2]:
# 동요 '산토끼'에서 '토'는 몇 번 나올까요
def get_char_count(lyric, char):
    count = 0
    for i in lyric:
        if(i == char):
            count = count + 1
    return count

lyric = """산토끼 토끼야. 어디를 가느냐. 깡충깡충 뛰면서. 어디를 가느냐.
산 고개 고개를. 나 혼자 넘어서. 토실토실 알밤을. 주워 올 테야."""
# 따옴표 1개, 2개, 3개 --> 긴 문장은 세개씩 사용


print(get_char_count(lyric, '토'))

4


### Numpy

In [3]:
import numpy as np

list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [9]:
np.random.rand(2,3)

array([[0.6620941 , 0.89115655, 0.21905963],
       [0.9431769 , 0.6386347 , 0.26453883]])

In [10]:
arr2 = np.arange(16)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr2.shape

(16,)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [16]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
arr[5]

5

In [18]:
arr[-1]

15

In [19]:
arr[5:8]

array([5, 6, 7])

In [20]:
np.zeros((2,3),dtype=int)
# np.zeros(shape, datatype)

array([[0, 0, 0],
       [0, 0, 0]])

In [42]:
scores = [80,90,70,65,85,95,90,80,75,80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [43]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [44]:
score_arr[score_arr >= 90]

array([90, 95, 90])

In [46]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [47]:
np.save('array',score_arr)

In [48]:
load_arr = np.load('array.npy')
load_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [56]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [57]:
arr + 2

array([3, 4, 5, 6])

In [58]:
arr *2

array([2, 4, 6, 8])

In [60]:
list = [1,2,3,4]
list

[1, 2, 3, 4]

In [61]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [62]:
arr1 = np.arange(5,9)
arr1

array([5, 6, 7, 8])

In [63]:
arr + arr1

array([ 6,  8, 10, 12])

In [64]:
list1 = [5,6,7,8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]